// 書籍ビルド設定。entry は build/chapters/ (Mermaid 事前変換済み) を参照する
export default {
  title: 'TCG デザインの教科書',
  author: 'Javakky (仮名義)',
  language: 'ja',
  theme: '@vivliostyle/theme-techbook',
  size: 'JIS-B5',
  toc: true,
  entry: [
    'build/chapters/00_preface.md',
    'build/chapters/intro.md',
    'build/chapters/part1_intro.md',
    'build/chapters/ch01.md',
    'build/chapters/ch02.md',
    'build/chapters/ch03.md',
    'build/chapters/part2_intro.md',
    'build/chapters/ch04.md',
    'build/chapters/ch05.md',
    'build/chapters/ch06.md',
    'build/chapters/ch07.md',
    'build/chapters/ch08.md',
    'build/chapters/part3_intro.md',
    'build/chapters/ch09.md',
    'build/chapters/ch10.md',
    'build/chapters/part4_intro.md',
    'build/chapters/ch11.md',
    'build/chapters/ch12.md',
    'build/chapters/ch13.md',
    'build/chapters/part5_intro.md',
    'build/chapters/ch14.md',
    'build/chapters/ch15.md',
    'build/chapters/part6_intro.md',
    'build/chapters/ch16.md',
    'build/chapters/ch17.md',
    'build/chapters/appendix_a.md',
    'build/chapters/appendix_b.md',
    'build/chapters/appendix_c.md',
    'build/chapters/appendix_d.md',
    'build/chapters/colophon.md',
  ],
  output: [
    { path: 'output/tcg-design-textbook.pdf', format: 'pdf' },
    { path: 'output/tcg-design-textbook.epub', format: 'epub' },
  ],
  workspaceDir: '.vivliostyle',
};
